### ISSUE TITLE
Compile errors with rust stable

### ISSUE THREAD

**Issue by newAM** [rust-embedded/register-rs#8]
in `lib.rs` it says this in the documentation:
```rust
//! This crate is guaranteed to compile on stable Rust 1.39 and up. It *might* compile with older
//! versions but that may change in any new patch release.
```

but it does not build on rust stable
```
   Compiling tock-registers v0.6.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tock-registers-0.6.0/src/lib.rs:5:1
  |
5 | #![feature(const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^
```
```
rustc 1.48.0 (7eac88abb 2020-11-16
```

Should this be able to compile on stable or does the documentation just need to be updated?

P.S. Thanks for making this crate!

**Comment by andre-richter** [comment]
Hmm, indeed. This seems like an error in the documentation.

The `const_fn` is needed, and hence this will only work with a nightly toolchain. I'll update this in a minute.

Thanks for pointing this out.
